### ISSUE TITLE
Error: Samples must be provided in increasing order of cumulative value.

### ISSUE THREAD

**Issue by paulomorgado** [jlfwong/speedscope#310] opened 2020-09-24 11:32 UTC
When importing a trace, I get this error:

```
Error: Samples must be provided in increasing order of cumulative value. Last sample was 16047.911199999999, this sample was 11524.4362
    at n._leaveFrame (speedscope.c2e23fed.js:formatted:9635)
    at n.leaveFrame (speedscope.c2e23fed.js:formatted:9642)
    at speedscope.c2e23fed.js:formatted:9858
    at a (speedscope.c2e23fed.js:formatted:9861)
    at speedscope.c2e23fed.js:formatted:9885
    at Array.map (<anonymous>)
    at s (speedscope.c2e23fed.js:formatted:9885)
    at import.c3382116.js:111
    at Generator.next (<anonymous>)
    at s (import.c3382116.js:111)
```

Neither `16047.911199999999` or `11524.4362` are on the trace.

How can I debug this?

**Comment by bjorn3** [comment] 2020-09-24 12:33
What did you use to create the profile?

**Comment by paulomorgado** [comment] 2020-09-24 14:30
A tool I'm building to convert MSBuild binary logs to speedscope.

Here's the file: https://gist.github.com/paulomorgado/f5f45e61527f5a14877615781f71fc1d

**Comment by bjorn3** [comment] 2020-09-24 16:08
`16047.911199999999` is at https://gist.github.com/paulomorgado/f5f45e61527f5a14877615781f71fc1d#file-speedscope-json-L11884
`11524.4362` is at https://gist.github.com/paulomorgado/f5f45e61527f5a14877615781f71fc1d#file-speedscope-json-L20089

**Comment by paulomorgado** [comment] 2020-09-24 16:12
Right! My bad! I won't blame it on the text editor. 😄

**Comment by jlfwong** [comment] 2020-09-24 19:09
Sounds like you've figured out the cause here? I'm going to close this since I don't think speedscope needs to do anything else here, but let me know if you think otherwise.

**Closed by jlfwong** 2020-09-24 19:09 UTC
