### ISSUE TITLE
Error loading chrome tracing file generated by ninjatracing

### ISSUE THREAD

**Issue by e4lam** [jlfwong/speedscope#255] opened 2020-01-21 13:52 UTC
When I try to load a chrome tracing file generated by ninjatracing in speedscope, I get an error like this:
```
Failed to load format Error: Samples must be provided in increasing order of cumulative value. Last sample was 1000579000460000, this sample was 1043000
    at n._enterFrame (speedscope.75eb7d8e.js:153)
    at n.enterFrame (speedscope.75eb7d8e.js:153)
    at o (import.a03c2bef.js:109)
    at p (import.a03c2bef.js:109)
    at import.a03c2bef.js:111
    at Generator.next (<anonymous>)
    at s (import.a03c2bef.js:111)
```
Is this because it requires that the time stamp ("ts") values be sorted? In my chrome tracing file, it just has a bunch of samples with "ts" and "dur" values. Can this restriction be lifted? Or provide an option to sort first after loading?

**Comment by jlfwong** [comment] 2020-01-21 19:29
Hi @e4lam!

If you could provide a sample trace that fails to import, that would be helpful for debugging! This does sound like a bug to me, and possibly a recent regression.

Thanks!

**Comment by e4lam** [comment] 2020-01-21 20:12
Here's a redacted and reduced sample:
[bug_tracing.json.txt](https://github.com/jlfwong/speedscope/files/4093488/bug_tracing.json.txt)

**Comment by jlfwong** [comment] 2020-01-21 21:13
That's great, thanks for providing that! I'll try to take a look in the next few weeks

**Comment by jlfwong** [comment] 2020-02-06 06:27
@e4lam Okay I looked at the trace and debugged a bit.

Speedscope does sort timestamps before import, since that's required by the spec. The problem is that the `ts` field in those traces are strings instead of numbers. 

While the spec for the chrome tracing format doesn't explicitly forbid this, all of the examples use numbers rather than strings for fields that would be logically numerical

![image](https://user-images.githubusercontent.com/150329/73910439-33ba5380-4864-11ea-98ed-fc97aaafa603.png) (from https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.uxpopqvbjezh)

It seems, however, like chrome://tracing does support this. Which is... kind of a weird choice IMO.

After digging around int he chrome://tracing code for a while, I think it's entirely an accident that strings are supported.

Here's the trace that led me to conclude that:

- https://github.com/catapult-project/catapult/blob/82f1741bbfa3a24eebace418c12cff5aca208ef2/tracing/tracing/extras/importer/trace_event_importer.html#L497-L504
- https://github.com/catapult-project/catapult/blob/82f1741bbfa3a24eebace418c12cff5aca208ef2/tracing/tracing/extras/importer/trace_event_importer.html#L3356-L3368
- https://github.com/catapult-project/catapult/blob/82f1741bbfa3a24eebace418c12cff5aca208ef2/tracing/tracing/base/unit.html#L253-L256
- https://github.com/catapult-project/catapult/blob/11513e359cd60e369bbbd1f4f2ef648c1bccabd0/tracing/tracing/base/unit_scale.html#L108

The key line in the deepest part of the stack is this:

```
return value * (fromScale.value / toScale.value);
```

By the total accident that is JavaScript type coercion, in the process of attempting to convert from microseconds into milliseconds, this effectively does `"9482146000" * 1000` which coerces the string into a number.

I could support this in speedscope too, but this is IMO a bug in ninjatracing that it outputs strings instead of numbers, so I'd rather the bug be fixed there, since chrome tracing supports this by accident rather than on purpose, and the spec doesn't mention anything about supporting strings in the `ts` field.

So I'm going to close this for now.

**Closed by jlfwong** 2020-02-06 06:27 UTC

**Comment by e4lam** [comment] 2020-02-06 20:55
Thanks for looking into this @jlfwong ! This was an easy fix to ninjatracing but then I found that I can't use speedscope anyways. The profile I've got is from doing a build so it's all separated into individual events that have no relationships to each other. Without stack information, it looks like the regular chrome://tracing is better anyways because I can see all the events in relation to each other in parallel. Well, except for the fact that it's slow and the UI is buggy.
