### ISSUE TITLE
Website JS fails to load

### ISSUE THREAD

**Issue by emirb** [jlfwong/speedscope#186] opened 2018-10-30 11:17 UTC
https://www.speedscope.app/

Getting following issues:
`speedscope.7dbab0a6.js:93 Uncaught Error: Setup failure`
`demangle-cpp.6caf93ee.js:1 Uncaught Error: Cannot find module '132'`
`demangle-cpp.6caf93ee.js:1 Uncaught (in promise) Error: Cannot find module '104'`

**Comment by jlfwong** [comment] 2018-10-30 15:52
Hi @emirb! Thanks for reporting.

That's strange. I've had those issues locally before, but never on the production site. I also can't reproduce this at the moment. I just tried in Chrome, Safari, and Firefox on macOS, and they all seem to load okay.

Can you still reproduce this? If not, can you provide some more information about your OS/browser setup?

Closing this for now since I can't reproduce, but I'll re-open if this is still reproducible for you.

**Closed by jlfwong** 2018-10-30 15:52 UTC
