### ISSUE TITLE
Show events across multiple threads in the same process?

### ISSUE THREAD

**Issue by e4lam** [jlfwong/speedscope#257] opened 2020-02-07 17:32 UTC
In my regression test benchmark, I've got it outputting chrome://tracing complete samples that all use the same process but with different thread ids. In chrome://tracing, this shows up with nice horizontal bars across all threads in multiple rows. Is there a way to see data that way in speedscope?

**Comment by jlfwong** [comment] 2020-02-07 19:58
Hi again!

Unfortunately not. I agree this is really useful, but it's also a lot of work. I don't have any ETA on when that work is going to get done, so no promises, sorry!

I'm closing this as a duplicate of #117.

**Closed by jlfwong** 2020-02-07 19:58 UTC

**Comment by e4lam** [comment] 2020-02-07 22:15
Ah, I should have checked if there were duplicates. I figured I'd ask anyways. Thanks!
