### ISSUE TITLE
Cannot zoom 100% vertically

### ISSUE THREAD

**Issue by naftaly** [jlfwong/speedscope#482] opened 2024-10-09 21:00 UTC
You can easily zoom horizontally, but it's not possible to fill the screen vertically.

**Comment by jlfwong** [comment] 2024-10-10 03:33
Hi @naftaly! This is by design -- can you explain what your use case is? You can zoom out the entire interface using browser zoom (switch to the URL bar and hit cmd/ctrl-+)

**Comment by naftaly** [comment] 2024-10-18 01:59
I’ll have to try the browser zoom with the tool. It just seems like I should be able to adjust the zoom rectangle in the track to show everything, no special use case other than simply using the tool and expecting to to be possible.

**Comment by jlfwong** [comment] 2024-10-18 17:56
Gotcha -- I'm going to close this for now since this is expected behavior

**Closed by jlfwong** 2024-10-18 17:56 UTC
